// Group members: Richy Manzo, Andreas Hitt, Esteban Mora
// Instructor: Prof. Kanemoto
// Class: CPSC-25
// Assessment: Music Player 
// All files generated by Gemini 3 Fast, prompted by Andreas Hitt and Richy Manzo

#include <SoftwareSerial.h>
#include "AudioPlayer.h"
#include "Playlist.h"

// --- Global Objects ---
// These instances "ghost" the logic until the .cpp files are finished.
AudioPlayer player(2,3);
Playlist myPlaylist;

void setup() {
  Serial.begin(9600);
  while (!Serial) { ; } // Wait for Serial Monitor to open

  Serial.println(F("--- MP3 System Initializing ---"));

  // Ghost: This will eventually initialize SoftwareSerial and DFPlayer
  player.init(); 

  // Ghost: This will populate the 8+ tracks in the array
  myPlaylist.initializeTracks(); 

  showMenu();
}

void loop() {
  if (Serial.available() > 0) {
    String input = Serial.readStringUntil('\n');
    input.trim(); // Remove whitespace/newline

    if (input.length() == 0) return;

    // --- Command Parser ---
    
    // Play command: "p 5"
    if (input.startsWith("p ")) {
      int trackNum = input.substring(2).toInt();
      player.playTrack(trackNum);
    }
    
    // Navigation
    else if (input == "n") {
      player.nextTrack();
    }
    else if (input == "b") {
      player.previousTrack();
    }
    
    // Playback Controls
    else if (input == "pause") {
      player.pause();
    }
    else if (input == "stop") {
      player.stop();
    }
    
    // Volume: "v 20"
    else if (input.startsWith("v ")) {
      int vol = input.substring(2).toInt();
      player.setVolume(vol);
    }
    
    // Playlist Management
    else if (input == "list") {
      myPlaylist.listTracks();
    }
    
    // Search: "find title"
    else if (input.startsWith("find ")) {
      String keyword = input.substring(5);
      myPlaylist.linearSearch(keyword);
    }
    
    // Sort
    else if (input == "sort") {
      myPlaylist.manualSort();
    }
    
    // Help menu
    else if (input == "help") {
      showMenu();
    }
    
    // Invalid Command handling
    else {
      Serial.print(F("Unknown command: "));
      Serial.println(input);
    }
  }
}

void showMenu() {
  Serial.println(F("\n======= COMMAND MENU ======="));
  Serial.println(F("p <num>  : Play track number"));
  Serial.println(F("n        : Next track"));
  Serial.println(F("b        : Previous track"));
  Serial.println(F("pause    : Toggle Pause/Resume"));
  Serial.println(F("stop     : Stop playback"));
  Serial.println(F("v <0-30> : Set volume"));
  Serial.println(F("list     : Display all tracks"));
  Serial.println(F("find <k> : Search by keyword"));
  Serial.println(F("sort     : Sort playlist (Manual)"));
  Serial.println(F("help     : Show this menu"));
  Serial.println(F("============================\n"));
}
